name: Create Ivy Map Map

on:
  push:
    branches:
      - main # Set a branch to deploy


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    
    steps:
      - name: Contributor Map
        uses: tunaitis/contributor-map@v1 
        with:
          repository: unifyai/ivy
          output: data/ivy.svg
