name: Create Ivy Map Map

on:
  push:
    branches:
      - main # Set a branch to deploy

permissions: read-all|write-all

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Contributor Map
        uses: tunaitis/contributor-map@v1 
        with:
          repository: unifyai/ivy
          output: data/ivy.svg
