name: Create Ivy Map Map

on:
  push:
    branches:
      - main # Set a branch to deploy


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Ivy Map
        uses: tunaitis/contributor-map@v1 
        with:
          repository: unifyai/ivy
          output: data/ivy.svg
      - name: Open Sauced Map
        uses: tunaitis/contributor-map@v1 
        with:
          repository: open-sauced/open-sauced
          output: data/open_sauced.svg
